const fs = require("fs");
const outputJson = require("./output.json");

// Must run node index first to create output.json file

// prettier-ignore
const nameMappings = {
    "PD TOMATO ROMA XL": "Tomatoes",
    "RICE PARBOIL BAG": "Rice 50lb Bag",
    "RICE PARBOIL CUBE  1/50#": "Rice 50lb Box",
    "PD CABB RED SHRD": "Shredded Red Cabbage",
    "PD GARLIC SPAINPLD": "Peeled Garlic",
    "PD TOFU EXTRA FIRM": "Tofu",
    "PD LETT ROMAINE HT": "Lettuce",
    "YOG DAHI W/M JF    5#": "Dahi Yogurt",
    "BF HAL CHUCK ROLL": "Beef",
    "CHX HAL THIGH CVP": "Chicken",
    "LAMB GROUND": "Ground Lamb",
    "CONT#3 TO GO KRAFT 64Z": "Salad/Platter Containers",
    "DIET COKE          12Z": "Diet Coke",
    "COKE CLASSIC       12Z": "Coke Cans",
    "MAYO CHEFS QUALITY 4GL": "Mayo",
    "TORT WHT GRDITA13": "Wheat Wraps",
    "BAG BRN SOS 8#": "Medium Paper Bag",
    "TOM PUREE 1.06 ISB": "Tomato Puree",
    "JUICE LEMON GAL    4/1GAL": "Lemon Juice",
    "MUSTARD YLW FRENCH 4/105Z": "Mustard",
    "MEXICAN COKE       500ML": "Large Mexican Coke (500ml)",
    "CHZ FETA CRUMB ITH 5#": "Feta Cheese",
    "PD SPINACH CLEAN": "Spinach",
    "PD CUCUMBER SEL 72": "Cucumber",
    "GLOVE VNL MD PF": "Medium Gloves",
    "SPC TURMERIC GRND  1LB": "Turmeric",
    "OIL CANOLA C/PRIDE 6/1GAL": "Canola Oil",
    "SPC OREGANO GREEK  24Z": "Greek Oregano",
    "PEPPER BAN RNGMIL": "Banana Peppers",
    "TIMS HAW MIX PACK": "Tim's Hawaiian Chips",
    "KETCHUP HUNTS      #10": "Ketchup",
    "BAG BRN SOS 1/6": "Large To Go Bags",
    "TIMS VARIETY PACK  30CT": "Tim's Variety Chips",
    "COKE ZERO          12Z": "Coke Zero",
    "TORT SPNACH WRP12": "Spinach Wraps",
    "BAG SANDWICH-DX18": "#18 Bags",
    "SPC BAY LVS WHL    2Z": "Bay Leaves",
    "BAG BRN SOS 4#": "Small Bags",
    "PDU ITALIAN PARSLE Y": "Flat Leaf Parsley",
    "GLOVE VNL MD PF": "Medium Gloves",
    "SPC PEPR BLK GRND  5LB": "Black Pepper",
    "PAPER WRAP 15X16": "Sandwich Wrap 15x16",
    "LNR 40X46 16M NAT": "Trash Liner - natural",
    "PDU LEMON 5#": "Lemons",
    "YOGURT PLN JF 32#": "(do not order) JF 32# Yogurt",
    "SPC ONION PWDR": "Onion Powder",
    "SPC GARLIC POWDER  5LB": "Garlic Powder",
    "SPC DILL WEED 2#": "Dill Weed",
    "VINEGAR APL CIDER  5%": "Apple Cider Vinegar",
    "REG ROLL VPT313": "Register Rolls",
    "FORK PS BLK": "Forks",
    "SALT KOSHER MORTON": "Salt",
    "PD HRB DILL 1LB": "Fresh Dill",
    "ORANGE THUN CITRUS": "Orange Thunder Cleaner",
    "PD CABB COLESLAW": "(do not order) coleslaw",
    "FANTA ORANGE       355ML": "Mexican Fanta",
    "SPC PAPRIKA        4.5LB": "Paprika",
    "SPC CORIANDR SD GD 14Z": "Ground Coriander",
    "WRPS DP12 SPINACH 10CT": "(do not order) Spinach Wraps",
    "DAWN ORIGINAL PUMP": "Dish Soaps",
    "FOIL 12X10.75": "Foil Squares",
    "MEXICAN COKE       355ML": "Mexican Coke 355ml",
    "SCRUBBER S/S 50GR": "Dish Hand Sponge",
    "RICE PARBOIL CUBE  1/25#": "Rice 25lb",
    "CHX THIGH MEAT CVP": "(do not order) Chicken",
    "SOUR CREAM BULK JF": "(do not order) Sour Cream",
    "PD CABB RED 45LB": "Red Cabbage Heads",
    "PD ONION YLW BAGS": "Yellow Onions",
    "PD TOMATO 25LB XL": "Tomatoes",
    "BF HAL RIBEYE      NEB": "(do not order) ribeye",
    "FORK MD BK WRP PP": "(do not order) forks",
    "BAG BRN SOS 6#": "(do not order) #6 bags",
    "PAPER WRAP-NK1516": "(do not order) sandwich wraps",
    "LNR 38X58 17M NAT": "(do not order) trash liners",
    "FOIL ROLL 18X1000": "Heavy Duty Foil",
    "PD GARLIC SPAINPLD": "(do not order) garlic",
    "PD CUCUMBER HH BLK": "(do not order) cucumber",
    "SPC PEPR CAYENNE": "Cayenne Pepper",
    "TOWEL H/W WHT EMBS PS": "(do not order) paper towel",
    "KNORR VEG LQD BASE": "Knorr Veggie Broth Base",
    "FANTA ORANGE MEX   500ML": "(do not order) Large Fanta",
    "BAG SANDWICH-PB18": "(do not order) 18 bags",
    "PLATE PULP 9 WHT": "(do not order) plates",
    "PAN S/TBL 1/2DP    SUNSET": "(do not order) Aluminium Pans",
    "SINK STRAINR LARGE": "Sink Strainer",
    "CUP SFL 3.25ZSNSET": "Sauce Soufle Cups",
    "LID SFL 3.25-5Z": "Sauce Soufle Cup Lids",
    "BARINSE SANITIZER": "3 Comp Sink Sanitizer",
    "CHZ FETA PAIL 9#": "(do not order) 9# feta",
    "TRAY-FOOD 300#     3.#": "(do not order) food tray",
    "APRON STRIP CHALK": "(do not order) aprons",
    "FOIL INSUL-14X16": "Foil Sandwich Wraps 14x16",
    "SPC PEPR BLK 18MSH 5LB": "(do not order) msh blk pepper",
    "NAP INTERFOLD WHT  2PLY": "(do not order) white napkins",
    "FLOUR CRN MSCA     4#": "Corn Flour",
    "KNORR BASE BF LIQU": "(do not order) KNORR BASE BF LIQU",
    "TOWEL C/P 2-PLY    PS": "Paper Towels",
    "FORK BLK WRP PS": "(do not order) forks",
    "NAP INTERFOLD NAT  2PLY": "Napkins",
    "TOWEL C/P 2-PLY    PS": "(do not order) paper towel",
    "CHX HAL WING WHOLE": "(do not order) halal wings",
    "PDU TOMATO ROMA 5#": "(do not order) roma five pound",
    "PDU CABB RED 3 CT": "(do not order) 3 ct cabbage",
    "BF CHUCK ROLL SEL  R/W": "(do not order) chuck roll",
    "C&H SUGAR GRAN     25#": "Sugar 25lb",
    "PD LETT GRN LEAF": "(do not order) green leaf",
    "PD LETT ROMAINE": "Lettuce (whole heads)",
    "BAG BRN SOS 1/6 70": "(do not order) big bags",
    "CONT#3 TO GO WHITE 64Z": "(do not order) white to go",
    "PLA FORK": "(do not order) forks",
    "BAG ZIP FRZ 2GAL   DB ZP": "(do not order) zip locks",
    "SOFTSOAP ANTIBCTRL": "Hand Soap",
    "TOWEL H/W KRAFT    PS": "Paper Towel",
    "PD ONION YEL JBO": "(do not order) onions",
    "CHX THIGH BLKLABL  40#FRZ": "(do not order) blk lbl chicken",
    "MOP BLUE MED LOOP": "Mop Head",
    "MAYO CHEFS QUALITY 1GL": "(do not order) 1gl mayo",
    "SPC PEPR WHT GRND  1#": "(do not order) Ground White Pepper",
    "BROOM ANGLE UNFLAG": "Broom",
    "LINER PLA24X32     13GAL": "(do not order) small trash liner",
    "STEAK WEIGHT IRON  GRY EA": "(do not order)",
    "LC HAMBURGER TRNR": "(do not order)",
    "QUICK WAY MOP KIT": "Mop With Head and Handle",
    "MICROFIBER TWL GRN 12CT": "(do not order) micro fiber blue",
    "MICROFBR TWLS BLUE 12CT": "(do not order) micro fiber green",
    "DEX TURNER HAMB": "(do not order)",
    "SAUCE MUSHROOM SOY 63.5Z": "(do not order)",
    "KIKO SOY TAMARI GF": "(do not order)",
    "BASTING COVER 10": "(do not order)",
    "SPC PEPR WHT GRND  5LB": "Ground White Pepper",
    "SPC THYME GRND     12Z": "(do not order)",
    "BAG HNDL BRN MISSY": "(do not order)",
    "KTCHN ROLL TWL BRN": "(do not order)",
    "SPC CUMIN SEED GRD 5#": "Cummin",
    "COKE DIET          16.9Z": "(do not order)"
};

const result = outputJson.map((item) => {
  return {
    ...item,
    name: nameMappings[item.vendorProductName] || "",
  };
});

console.log(result);

fs.writeFile("outputWithNames.json", JSON.stringify(result, null, 2), (err) => {
  if (err) {
    console.error("Error writing to file outputWithNames.json:", err);
  } else {
    console.log("CSV file processed and outputWithNames.json created.");
  }
});
